<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Ardalis.GuardClauses" Version="5.0.0" />
        <PackageVersion Include="AutoMapper" Version="16.1.1" />
        <PackageVersion Include="Dapper" Version="2.1.79" />
        <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageVersion Include="Mapster.DependencyInjection" Version="10.0.8" />
        <PackageVersion Include="MediatR" Version="14.1.0" />
        <PackageVersion Include="Microsoft.AspNetCore.Http" Version="2.3.13" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
        <PackageVersion Include="System.Linq.Dynamic.Core" Version="1.7.2" />
        <PackageVersion Include="LazyCache.AspNetCore" Version="2.4.0" />
		<PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.9" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9" />
		<PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.9" />
		<PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
		<PackageVersion Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.9" />
        <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9" />
        <PackageVersion Include="NSwag.AspNetCore" Version="14.1.0" />
        <PackageVersion Include="NSwag.MSBuild" Version="14.1.0" />
        <PackageVersion Include="Scalar.AspNetCore" Version="2.17.2" />
        <PackageVersion Include="ZymLabs.NSwag.FluentValidation.AspNetCore" Version="0.6.3" />
	</ItemGroup>
</Project>